# Generated by Django 5.0.1 on 2024-02-15 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_forget_password_code_user_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
