# Generated by Django 5.0.1 on 2024-02-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ref',
        ),
    ]
