# Generated by Django 5.0.1 on 2024-02-15 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
