# Generated by Django 5.0.1 on 2024-02-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='passport',
        ),
    ]
