# Generated by Django 5.0.1 on 2024-02-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Creator',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
