# Generated by Django 5.0.1 on 2024-02-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Creator',
            field=models.CharField(default='Ese', max_length=50),
        ),
    ]
