# Generated by Django 5.0.1 on 2024-02-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Creator',
            field=models.CharField(max_length=50),
        ),
    ]
