# Generated by Django 5.0.1 on 2024-02-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Creator',
        ),
    ]
