# Generated by Django 5.0.1 on 2024-02-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
